name: Run in container

on:
  workflow_call:

env:
  JULIA_CPU_TARGET: "generic"

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: julia:1.9.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Version info
        run: julia -e 'using InteractiveUtils; versioninfo()'
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        with:
          path: ~/.julia
          key: ${{ runner.os }}-container-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-container-
      - name: Install Julia dependencies
        run: julia --project=@. --color=yes -e 'import Pkg; Pkg.Registry.update(); Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Julia execution
        run: julia --project=@. run.jl
