name: Run in container

on:
  workflow_call:
    inputs:
      JULIA_CACHE:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: julia:1.9.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        if: ${{ inputs.JULIA_CACHE != '0'}}
        with:
          path: ~/.julia
          key: ${{ runner.os }}-container-${{ inputs.JULIA_CACHE }}-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-container-${{ inputs.JULIA_CACHE }}-
      - name: Install Julia dependencies
        run: julia --project=@. --color=yes -e 'import Pkg; Pkg.Registry.update(); Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Julia execution
        run: julia --project=@. run.jl
