name: Run regularly

on:
  workflow_call:

jobs:
  regular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read Julia version
        id: read_toml
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: 'Manifest.toml'
          field: 'julia_version'
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ steps.read_toml.outputs.value }}
          show-versioninfo: 'true'
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        with:
          path: ~/.julia
          key: ${{ runner.os }}-julia-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-
      - name: Install Julia dependencies
        run: julia --project=@. --color=yes -e 'import Pkg; Pkg.Registry.update(); Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Run the code
        run: julia --project=@. run.jl
