name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  JULIA_NUM_THREADS: auto
  JULIA_CPU_TARGET: generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1);broadwell

jobs:
  container-1:
    uses: ./.github/workflows/ci-container.yml

  container-2:
    needs: container-1
    uses: ./.github/workflows/ci-container.yml

  container-3:
    needs: container-2
    uses: ./.github/workflows/ci-container.yml

  container-4:
    needs: container-3
    uses: ./.github/workflows/ci-container.yml

  regular-1:
    uses: ./.github/workflows/ci-regular.yml

  regular-2:
    needs: regular-1
    uses: ./.github/workflows/ci-regular.yml
  regular-3:
    needs: regular-2
    uses: ./.github/workflows/ci-regular.yml
  regular-4:
    needs: regular-3
    uses: ./.github/workflows/ci-regular.yml
