name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JULIA_NUM_THREADS: auto
  JULIA_CPU_TARGET: generic

jobs:
  container-1:
    uses: ./.github/workflows/ci-container.yml
  container-2:
    needs: container-1
    uses: ./.github/workflows/ci-container.yml
  container-3:
    needs: container-2
    uses: ./.github/workflows/ci-container.yml
  container-4:
    needs: container-3
    uses: ./.github/workflows/ci-container.yml

  dfile-1:
    uses: ./.github/workflows/ci-dockerfile.yml
  dfile-2:
    needs: dfile-1
    uses: ./.github/workflows/ci-dockerfile.yml
  dfile-3:
    needs: dfile-2
    uses: ./.github/workflows/ci-dockerfile.yml
  dfile-4:
    needs: dfile-3
    uses: ./.github/workflows/ci-dockerfile.yml
