name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write
  pull-requests: write

env:
  NPROC: '4'
  JULIA_DEPOT_PATH: '~/.julia'
  JULIA_NUM_THREADS: 'auto'
  JULIA_CACHE: '1'

jobs:
  jupyter-book:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up workspace
        uses: colpal/actions-clean@v1
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read Julia version
        uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'Manifest.toml'
          field: 'julia_version'
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ steps.read_toml.outputs.value }}
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        if: ${{ env.JULIA_CACHE != '0'}}
        with:
          path: ${{ env.JULIA_DEPOT_PATH }}
          key: ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-${{ hashFiles('**/Manifest.toml') }}
      - name: Install Julia dependencies
        env:
          PYTHON: ${{ steps.python.outputs.python-path }}
        run: |
          julia --color=yes --project=@. -e 'import Pkg; Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Julia execution
        run: julia --color=yes --project=@. -e 'using DifferentialEquations; using ModelingToolkit; println("Hello")'
