name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write
  pull-requests: write

env:
  JULIA_DEPOT_PATH: '/srv/juliapkgs'
  JULIA_CACHE: '1'

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: julia:1.8.5
      env:
        JULIA_NUM_THREADS: 'auto'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        if: ${{ env.JULIA_CACHE != '0'}}
        with:
          path: ${{ env.JULIA_DEPOT_PATH }}
          key: ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-${{ hashFiles('**/Manifest.toml') }}
      - name: Install Julia dependencies
        env:
          PYTHON: ""
        run: |
          julia --color=yes --project=@. -e 'import Pkg; Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Julia execution
        run: julia --color=yes --project=@. -e 'println("Hello")'
