name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  JULIA_NUM_THREADS: auto
  JULIA_CPU_TARGET: generic

jobs:
  container-1:
    uses: ./.github/workflows/ci-container.yml
    with:
      JULIA_CACHE: '1'

  container-2:
    needs: container-1
    uses: ./.github/workflows/ci-container.yml
    with:
      JULIA_CACHE: '1'

  regular-1:
    uses: ./.github/workflows/ci-regular.yml
    with:
      JULIA_CACHE: '1'

  regular-2:
    needs: regular-1
    uses: ./.github/workflows/ci-regular.yml
    with:
      JULIA_CACHE: '1'
